os: linux
dist: xenial
cache: pip

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

services: xvfb

language: python
branches:
  only:
    - master


before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm

install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
  - pip install tox

jobs:
  include:
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=black
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=check_packaging

before_script:
  - "herbstluftwm &"
  - sleep 1

script:
  - QT_DEBUG_PLUGINS=1 tox
