version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "%(asctime)s|%(created)f|%(levelname).4s|%(filename)-15.15s|%(lineno)-3.3s|%(funcName)-10.10s|%(process)d|%(thread)d|%(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    stdout:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    stderr:
        class: logging.StreamHandler
        level: ERROR
        formatter: standard
        stream: ext://sys.stderr

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: log/info.csv
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: standard
        filename: log/errors.csv
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: NOTSET
        formatter: standard
        filename: log/debug.csv
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: log/critical.csv
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: log/warn.csv
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [stdout, debug_file_handler]
#    propagate: false

loggers:
    nodedge.node:
        handlers: [debug_file_handler]
#        handlers: [stdout, info]

    nodedge.logger:
        handlers: [stdout, debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.application_styler:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.edge:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.scene:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.scene_clipboard:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.utils:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.graphics_view:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false

    nodedge.graphics_scene:
        handlers: [debug_file_handler]
        level: DEBUG
        propagate: false
