name: Scan code with CodeQL

on:
  push:
    branches: [main]
#  schedule:
#    #        ┌───────────── minute (0 - 59)
#    #        │  ┌───────────── hour (0 - 23)
#    #        │  │ ┌───────────── day of the month (1 - 31)
#    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#    #        │  │ │ │ │
#    #        │  │ │ │ │
#    #        │  │ │ │ │
#    #        *  * * * *
#    - cron: '30 1 * * 0'

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
